run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-rules:
    - text: "coder now maintains this library at https://github.com/coder/websocket"
      linters:
        - staticcheck
