// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthAuditLog = `-- name: CreateAuthAuditLog :one
INSERT INTO auth_audit_logs (user_id, phone_e164, event, ip_address, user_agent, device_fingerprint, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, phone_e164, event, ip_address, user_agent, device_fingerprint, metadata, created_at
`

type CreateAuthAuditLogParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	PhoneE164         pgtype.Text `json:"phone_e164"`
	Event             string      `json:"event"`
	IpAddress         pgtype.Text `json:"ip_address"`
	UserAgent         pgtype.Text `json:"user_agent"`
	DeviceFingerprint pgtype.Text `json:"device_fingerprint"`
	Metadata          []byte      `json:"metadata"`
}

func (q *Queries) CreateAuthAuditLog(ctx context.Context, arg CreateAuthAuditLogParams) (AuthAuditLog, error) {
	row := q.db.QueryRow(ctx, createAuthAuditLog,
		arg.UserID,
		arg.PhoneE164,
		arg.Event,
		arg.IpAddress,
		arg.UserAgent,
		arg.DeviceFingerprint,
		arg.Metadata,
	)
	var i AuthAuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PhoneE164,
		&i.Event,
		&i.IpAddress,
		&i.UserAgent,
		&i.DeviceFingerprint,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, family_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, family_id, is_revoked, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	FamilyID  uuid.UUID          `json:"family_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.FamilyID,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, family_id, is_revoked, expires_at, created_at
FROM refresh_tokens
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE refresh_tokens
SET is_revoked = TRUE
WHERE user_id = $1
`

func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET is_revoked = TRUE
WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const revokeTokenFamily = `-- name: RevokeTokenFamily :exec
UPDATE refresh_tokens
SET is_revoked = TRUE
WHERE family_id = $1
`

func (q *Queries) RevokeTokenFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeTokenFamily, familyID)
	return err
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (user_id, fcm_token, platform, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (fcm_token) DO UPDATE
SET user_id = EXCLUDED.user_id,
    platform = EXCLUDED.platform,
    updated_at = NOW()
RETURNING id, user_id, fcm_token, platform, created_at, updated_at
`

type UpsertDeviceParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FcmToken string    `json:"fcm_token"`
	Platform string    `json:"platform"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, upsertDevice, arg.UserID, arg.FcmToken, arg.Platform)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FcmToken,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
