// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: chat.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    match_id,
    sender_id,
    body,
    type,
    client_msg_id,
    media_url,
    metadata,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
RETURNING id, match_id, sender_id, body, type, client_msg_id, media_url, metadata, created_at, read_at
`

type CreateMessageParams struct {
	MatchID     uuid.UUID   `json:"match_id"`
	SenderID    uuid.UUID   `json:"sender_id"`
	Body        pgtype.Text `json:"body"`
	Type        string      `json:"type"`
	ClientMsgID pgtype.Text `json:"client_msg_id"`
	MediaUrl    pgtype.Text `json:"media_url"`
	Metadata    []byte      `json:"metadata"`
}

type CreateMessageRow struct {
	ID          int64              `json:"id"`
	MatchID     uuid.UUID          `json:"match_id"`
	SenderID    uuid.UUID          `json:"sender_id"`
	Body        pgtype.Text        `json:"body"`
	Type        string             `json:"type"`
	ClientMsgID pgtype.Text        `json:"client_msg_id"`
	MediaUrl    pgtype.Text        `json:"media_url"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.MatchID,
		arg.SenderID,
		arg.Body,
		arg.Type,
		arg.ClientMsgID,
		arg.MediaUrl,
		arg.Metadata,
	)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.SenderID,
		&i.Body,
		&i.Type,
		&i.ClientMsgID,
		&i.MediaUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices
WHERE user_id = $1 AND fcm_token = $2
`

type DeleteDeviceParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FcmToken string    `json:"fcm_token"`
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.Exec(ctx, deleteDevice, arg.UserID, arg.FcmToken)
	return err
}

const getActiveDevicesForUser = `-- name: GetActiveDevicesForUser :many
SELECT id, user_id, fcm_token, platform, updated_at
FROM devices
WHERE user_id = $1
ORDER BY updated_at DESC
`

type GetActiveDevicesForUserRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	FcmToken  string             `json:"fcm_token"`
	Platform  string             `json:"platform"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetActiveDevicesForUser(ctx context.Context, userID uuid.UUID) ([]GetActiveDevicesForUserRow, error) {
	rows, err := q.db.Query(ctx, getActiveDevicesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveDevicesForUserRow{}
	for rows.Next() {
		var i GetActiveDevicesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FcmToken,
			&i.Platform,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchParticipants = `-- name: GetMatchParticipants :one
SELECT user_a, user_b, unmatched_at
FROM matches
WHERE id = $1
`

type GetMatchParticipantsRow struct {
	UserA       uuid.UUID          `json:"user_a"`
	UserB       uuid.UUID          `json:"user_b"`
	UnmatchedAt pgtype.Timestamptz `json:"unmatched_at"`
}

func (q *Queries) GetMatchParticipants(ctx context.Context, id uuid.UUID) (GetMatchParticipantsRow, error) {
	row := q.db.QueryRow(ctx, getMatchParticipants, id)
	var i GetMatchParticipantsRow
	err := row.Scan(&i.UserA, &i.UserB, &i.UnmatchedAt)
	return i, err
}

const getMessageByClientMsgID = `-- name: GetMessageByClientMsgID :one
SELECT id, match_id, sender_id, body, type, client_msg_id, media_url, metadata, created_at, read_at
FROM messages
WHERE match_id = $1 AND client_msg_id = $2
LIMIT 1
`

type GetMessageByClientMsgIDParams struct {
	MatchID     uuid.UUID   `json:"match_id"`
	ClientMsgID pgtype.Text `json:"client_msg_id"`
}

type GetMessageByClientMsgIDRow struct {
	ID          int64              `json:"id"`
	MatchID     uuid.UUID          `json:"match_id"`
	SenderID    uuid.UUID          `json:"sender_id"`
	Body        pgtype.Text        `json:"body"`
	Type        string             `json:"type"`
	ClientMsgID pgtype.Text        `json:"client_msg_id"`
	MediaUrl    pgtype.Text        `json:"media_url"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
}

func (q *Queries) GetMessageByClientMsgID(ctx context.Context, arg GetMessageByClientMsgIDParams) (GetMessageByClientMsgIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByClientMsgID, arg.MatchID, arg.ClientMsgID)
	var i GetMessageByClientMsgIDRow
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.SenderID,
		&i.Body,
		&i.Type,
		&i.ClientMsgID,
		&i.MediaUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, match_id, sender_id, body, type, client_msg_id, media_url, metadata, created_at, read_at
FROM messages
WHERE id = $1
`

type GetMessageByIDRow struct {
	ID          int64              `json:"id"`
	MatchID     uuid.UUID          `json:"match_id"`
	SenderID    uuid.UUID          `json:"sender_id"`
	Body        pgtype.Text        `json:"body"`
	Type        string             `json:"type"`
	ClientMsgID pgtype.Text        `json:"client_msg_id"`
	MediaUrl    pgtype.Text        `json:"media_url"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
}

func (q *Queries) GetMessageByID(ctx context.Context, id int64) (GetMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.SenderID,
		&i.Body,
		&i.Type,
		&i.ClientMsgID,
		&i.MediaUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const getUserNotificationSettings = `-- name: GetUserNotificationSettings :one
SELECT id, locale, notification_settings
FROM users
WHERE id = $1
`

type GetUserNotificationSettingsRow struct {
	ID                   uuid.UUID `json:"id"`
	Locale               string    `json:"locale"`
	NotificationSettings []byte    `json:"notification_settings"`
}

func (q *Queries) GetUserNotificationSettings(ctx context.Context, id uuid.UUID) (GetUserNotificationSettingsRow, error) {
	row := q.db.QueryRow(ctx, getUserNotificationSettings, id)
	var i GetUserNotificationSettingsRow
	err := row.Scan(&i.ID, &i.Locale, &i.NotificationSettings)
	return i, err
}

const listMessagesAfter = `-- name: ListMessagesAfter :many
SELECT id, match_id, sender_id, body, type, client_msg_id, media_url, metadata, created_at, read_at
FROM messages
WHERE match_id = $1 AND id > $2
ORDER BY id ASC
LIMIT $3
`

type ListMessagesAfterParams struct {
	MatchID uuid.UUID `json:"match_id"`
	ID      int64     `json:"id"`
	Limit   int32     `json:"limit"`
}

type ListMessagesAfterRow struct {
	ID          int64              `json:"id"`
	MatchID     uuid.UUID          `json:"match_id"`
	SenderID    uuid.UUID          `json:"sender_id"`
	Body        pgtype.Text        `json:"body"`
	Type        string             `json:"type"`
	ClientMsgID pgtype.Text        `json:"client_msg_id"`
	MediaUrl    pgtype.Text        `json:"media_url"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
}

func (q *Queries) ListMessagesAfter(ctx context.Context, arg ListMessagesAfterParams) ([]ListMessagesAfterRow, error) {
	rows, err := q.db.Query(ctx, listMessagesAfter, arg.MatchID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesAfterRow{}
	for rows.Next() {
		var i ListMessagesAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.SenderID,
			&i.Body,
			&i.Type,
			&i.ClientMsgID,
			&i.MediaUrl,
			&i.Metadata,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT id, match_id, sender_id, body, type, client_msg_id, media_url, metadata, created_at, read_at
FROM messages
WHERE match_id = $1 AND ($2::int8 = 0 OR id < $2)
ORDER BY id DESC
LIMIT $3::int4
`

type ListMessagesBeforeParams struct {
	MatchID     uuid.UUID `json:"match_id"`
	BeforeID    int64     `json:"before_id"`
	ResultLimit int32     `json:"result_limit"`
}

type ListMessagesBeforeRow struct {
	ID          int64              `json:"id"`
	MatchID     uuid.UUID          `json:"match_id"`
	SenderID    uuid.UUID          `json:"sender_id"`
	Body        pgtype.Text        `json:"body"`
	Type        string             `json:"type"`
	ClientMsgID pgtype.Text        `json:"client_msg_id"`
	MediaUrl    pgtype.Text        `json:"media_url"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
}

func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]ListMessagesBeforeRow, error) {
	rows, err := q.db.Query(ctx, listMessagesBefore, arg.MatchID, arg.BeforeID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesBeforeRow{}
	for rows.Next() {
		var i ListMessagesBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.SenderID,
			&i.Body,
			&i.Type,
			&i.ClientMsgID,
			&i.MediaUrl,
			&i.Metadata,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessagesAsRead = `-- name: MarkMessagesAsRead :exec
UPDATE messages
SET read_at = NOW()
WHERE match_id = $1 
  AND sender_id != $2 
  AND read_at IS NULL 
  AND id <= $3
`

type MarkMessagesAsReadParams struct {
	MatchID  uuid.UUID `json:"match_id"`
	SenderID uuid.UUID `json:"sender_id"`
	ID       int64     `json:"id"`
}

func (q *Queries) MarkMessagesAsRead(ctx context.Context, arg MarkMessagesAsReadParams) error {
	_, err := q.db.Exec(ctx, markMessagesAsRead, arg.MatchID, arg.SenderID, arg.ID)
	return err
}

const updateMatchLastMessageAt = `-- name: UpdateMatchLastMessageAt :exec
UPDATE matches
SET last_message_at = $2
WHERE id = $1
`

type UpdateMatchLastMessageAtParams struct {
	ID            uuid.UUID          `json:"id"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
}

func (q *Queries) UpdateMatchLastMessageAt(ctx context.Context, arg UpdateMatchLastMessageAtParams) error {
	_, err := q.db.Exec(ctx, updateMatchLastMessageAt, arg.ID, arg.LastMessageAt)
	return err
}

const updateUserNotificationSettings = `-- name: UpdateUserNotificationSettings :exec
UPDATE users
SET notification_settings = $2
WHERE id = $1
`

type UpdateUserNotificationSettingsParams struct {
	ID                   uuid.UUID `json:"id"`
	NotificationSettings []byte    `json:"notification_settings"`
}

func (q *Queries) UpdateUserNotificationSettings(ctx context.Context, arg UpdateUserNotificationSettingsParams) error {
	_, err := q.db.Exec(ctx, updateUserNotificationSettings, arg.ID, arg.NotificationSettings)
	return err
}
