// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: discovery.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDiscoveryCandidates = `-- name: GetDiscoveryCandidates :many
SELECT 
    p.user_id,
    p.display_name,
    p.birthdate,
    p.gender,
    p.bio,
    p.job_title,
    p.education,
    p.height_cm,
    p.religion,
    p.city,
    p.region,
    ST_Y(p.geog::geometry) AS latitude,
    ST_X(p.geog::geometry) AS longitude,
    CASE WHEN p.geog IS NOT NULL AND $1::float8 != 0.0 AND $2::float8 != 0.0
         THEN ST_Distance(p.geog, ST_SetSRID(ST_MakePoint($2, $1), 4326)::geography) / 1000.0
         ELSE 0.0 END AS distance_km,
    p.verified,
    p.completeness_score,
    u.last_active_at,
    p.boost_until,
    (
        (1.0 / (1.0 + EXTRACT(EPOCH FROM (NOW() - u.last_active_at)) / 86400.0)) * 30.0 +
        (p.completeness_score * 0.2) +
        (CASE WHEN p.geog IS NOT NULL AND $1::float8 != 0.0 AND $2::float8 != 0.0
              THEN (1.0 / (1.0 + ST_Distance(p.geog, ST_SetSRID(ST_MakePoint($2, $1), 4326)::geography) / 10000.0)) * 20.0
              ELSE 10.0 END) +
        (CASE WHEN EXISTS (
            SELECT 1 FROM swipes sw 
            WHERE sw.swiper_id = p.user_id AND sw.target_id = $3 AND sw.direction IN ('like', 'super')
        ) THEN 50.0 ELSE 0.0 END) +
        (CASE WHEN (u.boost_until IS NOT NULL AND u.boost_until > NOW()) OR (p.boost_until IS NOT NULL AND p.boost_until > NOW())
              THEN 100.0 ELSE 0.0 END) +
        (random() * 5.0)
    )::float8 AS score
FROM profiles p
JOIN users u ON u.id = p.user_id
WHERE p.user_id != $3
  AND p.show_me = TRUE
  AND u.status = 'active'
  AND u.last_active_at >= NOW() - INTERVAL '30 days'
  AND (
      $4::text = ANY(p.interested_in)
      OR ($4::text = 'man' AND ('men' = ANY(p.interested_in) OR 'everyone' = ANY(p.interested_in)))
      OR ($4::text = 'woman' AND ('women' = ANY(p.interested_in) OR 'everyone' = ANY(p.interested_in)))
      OR 'everyone' = ANY(p.interested_in)
  )
  AND (
      p.gender = ANY($5::text[])
      OR (p.gender = 'man' AND ('men' = ANY($5::text[]) OR 'everyone' = ANY($5::text[])))
      OR (p.gender = 'woman' AND ('women' = ANY($5::text[]) OR 'everyone' = ANY($5::text[])))
      OR 'everyone' = ANY($5::text[])
  )
  AND EXTRACT(YEAR FROM age(CURRENT_DATE, $6::date)) BETWEEN p.age_min AND p.age_max
  AND EXTRACT(YEAR FROM age(CURRENT_DATE, p.birthdate)) BETWEEN $7::int4 AND $8::int4
  AND (
      $9::float8 <= 0.0 
      OR p.geog IS NULL 
      OR $1::float8 = 0.0 
      OR ST_DWithin(p.geog, ST_SetSRID(ST_MakePoint($2, $1), 4326)::geography, $9)
  )
  AND EXISTS (
      SELECT 1 FROM profile_photos ph
      WHERE ph.user_id = p.user_id AND ph.status IN ('approved', 'pending')
  )
  AND NOT EXISTS (
      SELECT 1 FROM blocks b
      WHERE (b.blocker_id = $3 AND b.blocked_id = p.user_id)
         OR (b.blocker_id = p.user_id AND b.blocked_id = $3)
  )
  AND NOT EXISTS (
      SELECT 1 FROM swipes s
      WHERE s.swiper_id = $3 AND s.target_id = p.user_id
  )
  AND NOT (p.user_id = ANY($10::uuid[]))
ORDER BY score DESC
LIMIT $11::int4
`

type GetDiscoveryCandidatesParams struct {
	MyLat          float64     `json:"my_lat"`
	MyLng          float64     `json:"my_lng"`
	UserID         uuid.UUID   `json:"user_id"`
	MyGender       string      `json:"my_gender"`
	MyInterestedIn []string    `json:"my_interested_in"`
	MyBirthdate    pgtype.Date `json:"my_birthdate"`
	AgeMin         int32       `json:"age_min"`
	AgeMax         int32       `json:"age_max"`
	RadiusMeters   float64     `json:"radius_meters"`
	ExcludedIds    []uuid.UUID `json:"excluded_ids"`
	ResultLimit    int32       `json:"result_limit"`
}

type GetDiscoveryCandidatesRow struct {
	UserID            uuid.UUID          `json:"user_id"`
	DisplayName       string             `json:"display_name"`
	Birthdate         pgtype.Date        `json:"birthdate"`
	Gender            string             `json:"gender"`
	Bio               pgtype.Text        `json:"bio"`
	JobTitle          pgtype.Text        `json:"job_title"`
	Education         pgtype.Text        `json:"education"`
	HeightCm          pgtype.Int4        `json:"height_cm"`
	Religion          pgtype.Text        `json:"religion"`
	City              pgtype.Text        `json:"city"`
	Region            pgtype.Text        `json:"region"`
	Latitude          interface{}        `json:"latitude"`
	Longitude         interface{}        `json:"longitude"`
	DistanceKm        float64            `json:"distance_km"`
	Verified          bool               `json:"verified"`
	CompletenessScore int32              `json:"completeness_score"`
	LastActiveAt      pgtype.Timestamptz `json:"last_active_at"`
	BoostUntil        pgtype.Timestamptz `json:"boost_until"`
	Score             float64            `json:"score"`
}

func (q *Queries) GetDiscoveryCandidates(ctx context.Context, arg GetDiscoveryCandidatesParams) ([]GetDiscoveryCandidatesRow, error) {
	rows, err := q.db.Query(ctx, getDiscoveryCandidates,
		arg.MyLat,
		arg.MyLng,
		arg.UserID,
		arg.MyGender,
		arg.MyInterestedIn,
		arg.MyBirthdate,
		arg.AgeMin,
		arg.AgeMax,
		arg.RadiusMeters,
		arg.ExcludedIds,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDiscoveryCandidatesRow{}
	for rows.Next() {
		var i GetDiscoveryCandidatesRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.Birthdate,
			&i.Gender,
			&i.Bio,
			&i.JobTitle,
			&i.Education,
			&i.HeightCm,
			&i.Religion,
			&i.City,
			&i.Region,
			&i.Latitude,
			&i.Longitude,
			&i.DistanceKm,
			&i.Verified,
			&i.CompletenessScore,
			&i.LastActiveAt,
			&i.BoostUntil,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileCardByUserID = `-- name: GetProfileCardByUserID :one
SELECT 
    p.user_id,
    p.display_name,
    p.birthdate,
    p.gender,
    p.bio,
    p.job_title,
    p.education,
    p.height_cm,
    p.religion,
    p.city,
    p.region,
    p.verified,
    p.completeness_score,
    u.last_active_at
FROM profiles p
JOIN users u ON u.id = p.user_id
WHERE p.user_id = $1 LIMIT 1
`

type GetProfileCardByUserIDRow struct {
	UserID            uuid.UUID          `json:"user_id"`
	DisplayName       string             `json:"display_name"`
	Birthdate         pgtype.Date        `json:"birthdate"`
	Gender            string             `json:"gender"`
	Bio               pgtype.Text        `json:"bio"`
	JobTitle          pgtype.Text        `json:"job_title"`
	Education         pgtype.Text        `json:"education"`
	HeightCm          pgtype.Int4        `json:"height_cm"`
	Religion          pgtype.Text        `json:"religion"`
	City              pgtype.Text        `json:"city"`
	Region            pgtype.Text        `json:"region"`
	Verified          bool               `json:"verified"`
	CompletenessScore int32              `json:"completeness_score"`
	LastActiveAt      pgtype.Timestamptz `json:"last_active_at"`
}

func (q *Queries) GetProfileCardByUserID(ctx context.Context, userID uuid.UUID) (GetProfileCardByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getProfileCardByUserID, userID)
	var i GetProfileCardByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Birthdate,
		&i.Gender,
		&i.Bio,
		&i.JobTitle,
		&i.Education,
		&i.HeightCm,
		&i.Religion,
		&i.City,
		&i.Region,
		&i.Verified,
		&i.CompletenessScore,
		&i.LastActiveAt,
	)
	return i, err
}
