// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	BlockerID uuid.UUID          `json:"blocker_id"`
	BlockedID uuid.UUID          `json:"blocked_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Device struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	FcmToken  string             `json:"fcm_token"`
	Platform  string             `json:"platform"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Interest struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Category  string             `json:"category"`
	Icon      pgtype.Text        `json:"icon"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Match struct {
	ID          uuid.UUID          `json:"id"`
	UserA       uuid.UUID          `json:"user_a"`
	UserB       uuid.UUID          `json:"user_b"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UnmatchedAt pgtype.Timestamptz `json:"unmatched_at"`
}

type Message struct {
	ID        int64              `json:"id"`
	MatchID   uuid.UUID          `json:"match_id"`
	SenderID  uuid.UUID          `json:"sender_id"`
	Body      pgtype.Text        `json:"body"`
	Type      string             `json:"type"`
	MediaID   pgtype.UUID        `json:"media_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
}

type Payment struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Provider    string             `json:"provider"`
	Reference   string             `json:"reference"`
	Amount      pgtype.Numeric     `json:"amount"`
	Currency    string             `json:"currency"`
	Status      string             `json:"status"`
	RawResponse []byte             `json:"raw_response"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Profile struct {
	UserID            uuid.UUID          `json:"user_id"`
	DisplayName       string             `json:"display_name"`
	Birthdate         pgtype.Date        `json:"birthdate"`
	Gender            string             `json:"gender"`
	InterestedIn      []string           `json:"interested_in"`
	Bio               pgtype.Text        `json:"bio"`
	JobTitle          pgtype.Text        `json:"job_title"`
	Education         pgtype.Text        `json:"education"`
	HeightCm          pgtype.Int4        `json:"height_cm"`
	Religion          pgtype.Text        `json:"religion"`
	Languages         []string           `json:"languages"`
	City              pgtype.Text        `json:"city"`
	Region            pgtype.Text        `json:"region"`
	Geog              interface{}        `json:"geog"`
	ShowMe            bool               `json:"show_me"`
	DistancePrefKm    int32              `json:"distance_pref_km"`
	AgeMin            int32              `json:"age_min"`
	AgeMax            int32              `json:"age_max"`
	Verified          bool               `json:"verified"`
	CompletenessScore int32              `json:"completeness_score"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ProfilePhoto struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Position  int32              `json:"position"`
	Blurhash  pgtype.Text        `json:"blurhash"`
	Width     pgtype.Int4        `json:"width"`
	Height    pgtype.Int4        `json:"height"`
	Variants  []byte             `json:"variants"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Report struct {
	ID         uuid.UUID          `json:"id"`
	ReporterID uuid.UUID          `json:"reporter_id"`
	ReportedID uuid.UUID          `json:"reported_id"`
	Reason     string             `json:"reason"`
	Details    pgtype.Text        `json:"details"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Plan      string             `json:"plan"`
	Status    string             `json:"status"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Swipe struct {
	SwiperID  uuid.UUID          `json:"swiper_id"`
	TargetID  uuid.UUID          `json:"target_id"`
	Direction string             `json:"direction"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	PhoneE164    string             `json:"phone_e164"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	IsPremium    bool               `json:"is_premium"`
	PremiumUntil pgtype.Timestamptz `json:"premium_until"`
	Locale       string             `json:"locale"`
}

type UserInterest struct {
	UserID     uuid.UUID `json:"user_id"`
	InterestID int32     `json:"interest_id"`
}
