// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addUserInterestByName = `-- name: AddUserInterestByName :exec
INSERT INTO user_interests (user_id, interest_id)
SELECT $1, id FROM interests WHERE LOWER(name) = LOWER($2)
ON CONFLICT DO NOTHING
`

type AddUserInterestByNameParams struct {
	UserID uuid.UUID `json:"user_id"`
	Lower  string    `json:"lower"`
}

func (q *Queries) AddUserInterestByName(ctx context.Context, arg AddUserInterestByNameParams) error {
	_, err := q.db.Exec(ctx, addUserInterestByName, arg.UserID, arg.Lower)
	return err
}

const clearUserInterests = `-- name: ClearUserInterests :exec
DELETE FROM user_interests WHERE user_id = $1
`

func (q *Queries) ClearUserInterests(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUserInterests, userID)
	return err
}

const countApprovedProfilePhotos = `-- name: CountApprovedProfilePhotos :one
SELECT COUNT(*) FROM profile_photos
WHERE user_id = $1 AND status = 'approved'
`

func (q *Queries) CountApprovedProfilePhotos(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovedProfilePhotos, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProfilePhotos = `-- name: CountProfilePhotos :one
SELECT COUNT(*) FROM profile_photos
WHERE user_id = $1
`

func (q *Queries) CountProfilePhotos(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProfilePhotos, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProfilePhoto = `-- name: CreateProfilePhoto :one
INSERT INTO profile_photos (id, user_id, position, blurhash, width, height, variants, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, position, blurhash, width, height, variants, status, created_at
`

type CreateProfilePhotoParams struct {
	ID       uuid.UUID   `json:"id"`
	UserID   uuid.UUID   `json:"user_id"`
	Position int32       `json:"position"`
	Blurhash pgtype.Text `json:"blurhash"`
	Width    pgtype.Int4 `json:"width"`
	Height   pgtype.Int4 `json:"height"`
	Variants []byte      `json:"variants"`
	Status   string      `json:"status"`
}

func (q *Queries) CreateProfilePhoto(ctx context.Context, arg CreateProfilePhotoParams) (ProfilePhoto, error) {
	row := q.db.QueryRow(ctx, createProfilePhoto,
		arg.ID,
		arg.UserID,
		arg.Position,
		arg.Blurhash,
		arg.Width,
		arg.Height,
		arg.Variants,
		arg.Status,
	)
	var i ProfilePhoto
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Position,
		&i.Blurhash,
		&i.Width,
		&i.Height,
		&i.Variants,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createVerification = `-- name: CreateVerification :one
INSERT INTO verifications (id, user_id, photo_url, pose, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, photo_url, pose, status, created_at, reviewed_at
`

type CreateVerificationParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	PhotoUrl string    `json:"photo_url"`
	Pose     string    `json:"pose"`
	Status   string    `json:"status"`
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) (Verification, error) {
	row := q.db.QueryRow(ctx, createVerification,
		arg.ID,
		arg.UserID,
		arg.PhotoUrl,
		arg.Pose,
		arg.Status,
	)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PhotoUrl,
		&i.Pose,
		&i.Status,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const deleteProfilePhoto = `-- name: DeleteProfilePhoto :exec
DELETE FROM profile_photos
WHERE id = $1 AND user_id = $2
`

type DeleteProfilePhotoParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteProfilePhoto(ctx context.Context, arg DeleteProfilePhotoParams) error {
	_, err := q.db.Exec(ctx, deleteProfilePhoto, arg.ID, arg.UserID)
	return err
}

const getPhotoByID = `-- name: GetPhotoByID :one
SELECT id, user_id, position, blurhash, width, height, variants, status, created_at
FROM profile_photos
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPhotoByID(ctx context.Context, id uuid.UUID) (ProfilePhoto, error) {
	row := q.db.QueryRow(ctx, getPhotoByID, id)
	var i ProfilePhoto
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Position,
		&i.Blurhash,
		&i.Width,
		&i.Height,
		&i.Variants,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPhotosByUserID = `-- name: GetPhotosByUserID :many
SELECT id, user_id, position, blurhash, width, height, variants, status, created_at
FROM profile_photos
WHERE user_id = $1
ORDER BY position ASC
`

func (q *Queries) GetPhotosByUserID(ctx context.Context, userID uuid.UUID) ([]ProfilePhoto, error) {
	rows, err := q.db.Query(ctx, getPhotosByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfilePhoto{}
	for rows.Next() {
		var i ProfilePhoto
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Position,
			&i.Blurhash,
			&i.Width,
			&i.Height,
			&i.Variants,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT user_id, display_name, birthdate, gender, interested_in, bio,
       job_title, education, height_cm, religion, languages, city, region,
       ST_Y(geog::geometry) AS latitude, ST_X(geog::geometry) AS longitude,
       show_me, distance_pref_km, age_min, age_max, verified, completeness_score,
       created_at, updated_at
FROM profiles
WHERE user_id = $1 LIMIT 1
`

type GetProfileByUserIDRow struct {
	UserID            uuid.UUID          `json:"user_id"`
	DisplayName       string             `json:"display_name"`
	Birthdate         pgtype.Date        `json:"birthdate"`
	Gender            string             `json:"gender"`
	InterestedIn      []string           `json:"interested_in"`
	Bio               pgtype.Text        `json:"bio"`
	JobTitle          pgtype.Text        `json:"job_title"`
	Education         pgtype.Text        `json:"education"`
	HeightCm          pgtype.Int4        `json:"height_cm"`
	Religion          pgtype.Text        `json:"religion"`
	Languages         []string           `json:"languages"`
	City              pgtype.Text        `json:"city"`
	Region            pgtype.Text        `json:"region"`
	Latitude          interface{}        `json:"latitude"`
	Longitude         interface{}        `json:"longitude"`
	ShowMe            bool               `json:"show_me"`
	DistancePrefKm    int32              `json:"distance_pref_km"`
	AgeMin            int32              `json:"age_min"`
	AgeMax            int32              `json:"age_max"`
	Verified          bool               `json:"verified"`
	CompletenessScore int32              `json:"completeness_score"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProfileByUserID(ctx context.Context, userID uuid.UUID) (GetProfileByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, userID)
	var i GetProfileByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Birthdate,
		&i.Gender,
		&i.InterestedIn,
		&i.Bio,
		&i.JobTitle,
		&i.Education,
		&i.HeightCm,
		&i.Religion,
		&i.Languages,
		&i.City,
		&i.Region,
		&i.Latitude,
		&i.Longitude,
		&i.ShowMe,
		&i.DistancePrefKm,
		&i.AgeMin,
		&i.AgeMax,
		&i.Verified,
		&i.CompletenessScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserInterests = `-- name: GetUserInterests :many
SELECT i.name
FROM interests i
JOIN user_interests ui ON i.id = ui.interest_id
WHERE ui.user_id = $1
ORDER BY i.name ASC
`

func (q *Queries) GetUserInterests(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserInterests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePhotoPosition = `-- name: UpdatePhotoPosition :exec
UPDATE profile_photos
SET position = $2
WHERE id = $1 AND user_id = $3
`

type UpdatePhotoPositionParams struct {
	ID       uuid.UUID `json:"id"`
	Position int32     `json:"position"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdatePhotoPosition(ctx context.Context, arg UpdatePhotoPositionParams) error {
	_, err := q.db.Exec(ctx, updatePhotoPosition, arg.ID, arg.Position, arg.UserID)
	return err
}

const updateProfileCompleteness = `-- name: UpdateProfileCompleteness :exec
UPDATE profiles
SET completeness_score = $2,
    show_me = CASE WHEN $3 = 0 THEN FALSE ELSE show_me END,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateProfileCompletenessParams struct {
	UserID            uuid.UUID   `json:"user_id"`
	CompletenessScore int32       `json:"completeness_score"`
	Column3           interface{} `json:"column_3"`
}

func (q *Queries) UpdateProfileCompleteness(ctx context.Context, arg UpdateProfileCompletenessParams) error {
	_, err := q.db.Exec(ctx, updateProfileCompleteness, arg.UserID, arg.CompletenessScore, arg.Column3)
	return err
}

const updateProfileLocation = `-- name: UpdateProfileLocation :exec
UPDATE profiles
SET geog = ST_SetSRID(ST_MakePoint($2, $3), 4326)::geography,
    city = $4,
    region = $5,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateProfileLocationParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
	City          pgtype.Text `json:"city"`
	Region        pgtype.Text `json:"region"`
}

func (q *Queries) UpdateProfileLocation(ctx context.Context, arg UpdateProfileLocationParams) error {
	_, err := q.db.Exec(ctx, updateProfileLocation,
		arg.UserID,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.City,
		arg.Region,
	)
	return err
}

const updateProfilePhoto = `-- name: UpdateProfilePhoto :exec
UPDATE profile_photos
SET blurhash = $2,
    width = $3,
    height = $4,
    variants = $5,
    status = $6
WHERE id = $1
`

type UpdateProfilePhotoParams struct {
	ID       uuid.UUID   `json:"id"`
	Blurhash pgtype.Text `json:"blurhash"`
	Width    pgtype.Int4 `json:"width"`
	Height   pgtype.Int4 `json:"height"`
	Variants []byte      `json:"variants"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateProfilePhoto(ctx context.Context, arg UpdateProfilePhotoParams) error {
	_, err := q.db.Exec(ctx, updateProfilePhoto,
		arg.ID,
		arg.Blurhash,
		arg.Width,
		arg.Height,
		arg.Variants,
		arg.Status,
	)
	return err
}

const upsertProfile = `-- name: UpsertProfile :one
INSERT INTO profiles (
    user_id, display_name, birthdate, gender, interested_in, bio,
    job_title, education, height_cm, religion, languages, city, region,
    show_me, distance_pref_km, age_min, age_max, completeness_score, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18, NOW()
)
ON CONFLICT (user_id) DO UPDATE SET
    display_name = COALESCE(EXCLUDED.display_name, profiles.display_name),
    birthdate = COALESCE(EXCLUDED.birthdate, profiles.birthdate),
    gender = COALESCE(EXCLUDED.gender, profiles.gender),
    interested_in = COALESCE(EXCLUDED.interested_in, profiles.interested_in),
    bio = COALESCE(EXCLUDED.bio, profiles.bio),
    job_title = COALESCE(EXCLUDED.job_title, profiles.job_title),
    education = COALESCE(EXCLUDED.education, profiles.education),
    height_cm = COALESCE(EXCLUDED.height_cm, profiles.height_cm),
    religion = COALESCE(EXCLUDED.religion, profiles.religion),
    languages = COALESCE(EXCLUDED.languages, profiles.languages),
    city = COALESCE(EXCLUDED.city, profiles.city),
    region = COALESCE(EXCLUDED.region, profiles.region),
    show_me = EXCLUDED.show_me,
    distance_pref_km = EXCLUDED.distance_pref_km,
    age_min = EXCLUDED.age_min,
    age_max = EXCLUDED.age_max,
    completeness_score = EXCLUDED.completeness_score,
    updated_at = NOW()
RETURNING user_id, display_name, birthdate, gender, interested_in, bio,
          job_title, education, height_cm, religion, languages, city, region,
          ST_Y(geog::geometry) AS latitude, ST_X(geog::geometry) AS longitude,
          show_me, distance_pref_km, age_min, age_max, verified, completeness_score,
          created_at, updated_at
`

type UpsertProfileParams struct {
	UserID            uuid.UUID   `json:"user_id"`
	DisplayName       string      `json:"display_name"`
	Birthdate         pgtype.Date `json:"birthdate"`
	Gender            string      `json:"gender"`
	InterestedIn      []string    `json:"interested_in"`
	Bio               pgtype.Text `json:"bio"`
	JobTitle          pgtype.Text `json:"job_title"`
	Education         pgtype.Text `json:"education"`
	HeightCm          pgtype.Int4 `json:"height_cm"`
	Religion          pgtype.Text `json:"religion"`
	Languages         []string    `json:"languages"`
	City              pgtype.Text `json:"city"`
	Region            pgtype.Text `json:"region"`
	ShowMe            bool        `json:"show_me"`
	DistancePrefKm    int32       `json:"distance_pref_km"`
	AgeMin            int32       `json:"age_min"`
	AgeMax            int32       `json:"age_max"`
	CompletenessScore int32       `json:"completeness_score"`
}

type UpsertProfileRow struct {
	UserID            uuid.UUID          `json:"user_id"`
	DisplayName       string             `json:"display_name"`
	Birthdate         pgtype.Date        `json:"birthdate"`
	Gender            string             `json:"gender"`
	InterestedIn      []string           `json:"interested_in"`
	Bio               pgtype.Text        `json:"bio"`
	JobTitle          pgtype.Text        `json:"job_title"`
	Education         pgtype.Text        `json:"education"`
	HeightCm          pgtype.Int4        `json:"height_cm"`
	Religion          pgtype.Text        `json:"religion"`
	Languages         []string           `json:"languages"`
	City              pgtype.Text        `json:"city"`
	Region            pgtype.Text        `json:"region"`
	Latitude          interface{}        `json:"latitude"`
	Longitude         interface{}        `json:"longitude"`
	ShowMe            bool               `json:"show_me"`
	DistancePrefKm    int32              `json:"distance_pref_km"`
	AgeMin            int32              `json:"age_min"`
	AgeMax            int32              `json:"age_max"`
	Verified          bool               `json:"verified"`
	CompletenessScore int32              `json:"completeness_score"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (UpsertProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertProfile,
		arg.UserID,
		arg.DisplayName,
		arg.Birthdate,
		arg.Gender,
		arg.InterestedIn,
		arg.Bio,
		arg.JobTitle,
		arg.Education,
		arg.HeightCm,
		arg.Religion,
		arg.Languages,
		arg.City,
		arg.Region,
		arg.ShowMe,
		arg.DistancePrefKm,
		arg.AgeMin,
		arg.AgeMax,
		arg.CompletenessScore,
	)
	var i UpsertProfileRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Birthdate,
		&i.Gender,
		&i.InterestedIn,
		&i.Bio,
		&i.JobTitle,
		&i.Education,
		&i.HeightCm,
		&i.Religion,
		&i.Languages,
		&i.City,
		&i.Region,
		&i.Latitude,
		&i.Longitude,
		&i.ShowMe,
		&i.DistancePrefKm,
		&i.AgeMin,
		&i.AgeMax,
		&i.Verified,
		&i.CompletenessScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
