// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAuthAuditLog(ctx context.Context, arg CreateAuthAuditLogParams) (AuthAuditLog, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phoneE164 string) (User, error)
	PurgeDeletedUsers(ctx context.Context, deletedAt pgtype.Timestamptz) (int64, error)
	RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	RevokeTokenFamily(ctx context.Context, familyID uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateUserLastActive(ctx context.Context, id uuid.UUID) error
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error)
}

var _ Querier = (*Queries)(nil)
