// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: swipes.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkMutualLike = `-- name: CheckMutualLike :one
SELECT EXISTS (
    SELECT 1 FROM swipes
    WHERE swiper_id = $1 AND target_id = $2 AND direction IN ('like', 'super')
)::bool AS is_mutual
`

type CheckMutualLikeParams struct {
	SwiperID uuid.UUID `json:"swiper_id"`
	TargetID uuid.UUID `json:"target_id"`
}

func (q *Queries) CheckMutualLike(ctx context.Context, arg CheckMutualLikeParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkMutualLike, arg.SwiperID, arg.TargetID)
	var is_mutual bool
	err := row.Scan(&is_mutual)
	return is_mutual, err
}

const countLikesYou = `-- name: CountLikesYou :one
SELECT COUNT(*) FROM swipes s
WHERE s.target_id = $1 
  AND s.direction IN ('like', 'super')
  AND NOT EXISTS (
      SELECT 1 FROM swipes my 
      WHERE my.swiper_id = $1 AND my.target_id = s.swiper_id
  )
  AND NOT EXISTS (
      SELECT 1 FROM blocks b 
      WHERE (b.blocker_id = $1 AND b.blocked_id = s.swiper_id)
         OR (b.blocker_id = s.swiper_id AND b.blocked_id = $1)
  )
`

func (q *Queries) CountLikesYou(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLikesYou, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBlock = `-- name: CreateBlock :exec
INSERT INTO blocks (blocker_id, blocked_id, created_at)
VALUES ($1, $2, NOW())
ON CONFLICT (blocker_id, blocked_id) DO NOTHING
`

type CreateBlockParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) error {
	_, err := q.db.Exec(ctx, createBlock, arg.BlockerID, arg.BlockedID)
	return err
}

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (id, user_a, user_b, created_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_a, user_b)
DO UPDATE SET unmatched_at = NULL
RETURNING id, user_a, user_b, created_at, unmatched_at
`

type CreateMatchParams struct {
	ID    uuid.UUID `json:"id"`
	UserA uuid.UUID `json:"user_a"`
	UserB uuid.UUID `json:"user_b"`
}

type CreateMatchRow struct {
	ID          uuid.UUID          `json:"id"`
	UserA       uuid.UUID          `json:"user_a"`
	UserB       uuid.UUID          `json:"user_b"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UnmatchedAt pgtype.Timestamptz `json:"unmatched_at"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (CreateMatchRow, error) {
	row := q.db.QueryRow(ctx, createMatch, arg.ID, arg.UserA, arg.UserB)
	var i CreateMatchRow
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.CreatedAt,
		&i.UnmatchedAt,
	)
	return i, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (id, reporter_id, reported_id, reason, details, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING id, reporter_id, reported_id, reason, details, status, created_at
`

type CreateReportParams struct {
	ID         uuid.UUID   `json:"id"`
	ReporterID uuid.UUID   `json:"reporter_id"`
	ReportedID uuid.UUID   `json:"reported_id"`
	Reason     string      `json:"reason"`
	Details    pgtype.Text `json:"details"`
	Status     string      `json:"status"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ID,
		arg.ReporterID,
		arg.ReportedID,
		arg.Reason,
		arg.Details,
		arg.Status,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ReportedID,
		&i.Reason,
		&i.Details,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSwipe = `-- name: DeleteSwipe :exec
DELETE FROM swipes 
WHERE swiper_id = $1 AND target_id = $2
`

type DeleteSwipeParams struct {
	SwiperID uuid.UUID `json:"swiper_id"`
	TargetID uuid.UUID `json:"target_id"`
}

func (q *Queries) DeleteSwipe(ctx context.Context, arg DeleteSwipeParams) error {
	_, err := q.db.Exec(ctx, deleteSwipe, arg.SwiperID, arg.TargetID)
	return err
}

const getLikesYouList = `-- name: GetLikesYouList :many
SELECT 
    s.swiper_id,
    s.direction,
    s.created_at
FROM swipes s
WHERE s.target_id = $1 
  AND s.direction IN ('like', 'super')
  AND NOT EXISTS (
      SELECT 1 FROM swipes my 
      WHERE my.swiper_id = $1 AND my.target_id = s.swiper_id
  )
  AND NOT EXISTS (
      SELECT 1 FROM blocks b 
      WHERE (b.blocker_id = $1 AND b.blocked_id = s.swiper_id)
         OR (b.blocker_id = s.swiper_id AND b.blocked_id = $1)
  )
ORDER BY s.created_at DESC
LIMIT $2::int4
`

type GetLikesYouListParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ResultLimit int32     `json:"result_limit"`
}

type GetLikesYouListRow struct {
	SwiperID  uuid.UUID          `json:"swiper_id"`
	Direction string             `json:"direction"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetLikesYouList(ctx context.Context, arg GetLikesYouListParams) ([]GetLikesYouListRow, error) {
	rows, err := q.db.Query(ctx, getLikesYouList, arg.UserID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLikesYouListRow{}
	for rows.Next() {
		var i GetLikesYouListRow
		if err := rows.Scan(&i.SwiperID, &i.Direction, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchBetweenUsers = `-- name: GetMatchBetweenUsers :one
SELECT id, user_a, user_b, created_at, unmatched_at
FROM matches
WHERE user_a = $1 AND user_b = $2
`

type GetMatchBetweenUsersParams struct {
	UserA uuid.UUID `json:"user_a"`
	UserB uuid.UUID `json:"user_b"`
}

type GetMatchBetweenUsersRow struct {
	ID          uuid.UUID          `json:"id"`
	UserA       uuid.UUID          `json:"user_a"`
	UserB       uuid.UUID          `json:"user_b"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UnmatchedAt pgtype.Timestamptz `json:"unmatched_at"`
}

func (q *Queries) GetMatchBetweenUsers(ctx context.Context, arg GetMatchBetweenUsersParams) (GetMatchBetweenUsersRow, error) {
	row := q.db.QueryRow(ctx, getMatchBetweenUsers, arg.UserA, arg.UserB)
	var i GetMatchBetweenUsersRow
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.CreatedAt,
		&i.UnmatchedAt,
	)
	return i, err
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, user_a, user_b, created_at, unmatched_at
FROM matches
WHERE id = $1
`

type GetMatchByIDRow struct {
	ID          uuid.UUID          `json:"id"`
	UserA       uuid.UUID          `json:"user_a"`
	UserB       uuid.UUID          `json:"user_b"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UnmatchedAt pgtype.Timestamptz `json:"unmatched_at"`
}

func (q *Queries) GetMatchByID(ctx context.Context, id uuid.UUID) (GetMatchByIDRow, error) {
	row := q.db.QueryRow(ctx, getMatchByID, id)
	var i GetMatchByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.CreatedAt,
		&i.UnmatchedAt,
	)
	return i, err
}

const getSwipe = `-- name: GetSwipe :one
SELECT swiper_id, target_id, direction, created_at
FROM swipes
WHERE swiper_id = $1 AND target_id = $2
`

type GetSwipeParams struct {
	SwiperID uuid.UUID `json:"swiper_id"`
	TargetID uuid.UUID `json:"target_id"`
}

func (q *Queries) GetSwipe(ctx context.Context, arg GetSwipeParams) (Swipe, error) {
	row := q.db.QueryRow(ctx, getSwipe, arg.SwiperID, arg.TargetID)
	var i Swipe
	err := row.Scan(
		&i.SwiperID,
		&i.TargetID,
		&i.Direction,
		&i.CreatedAt,
	)
	return i, err
}

const isBlocked = `-- name: IsBlocked :one
SELECT EXISTS (
    SELECT 1 FROM blocks
    WHERE (blocker_id = $1 AND blocked_id = $2)
       OR (blocker_id = $2 AND blocked_id = $1)
)::bool AS blocked
`

type IsBlockedParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) IsBlocked(ctx context.Context, arg IsBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlocked, arg.BlockerID, arg.BlockedID)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const listUserMatches = `-- name: ListUserMatches :many
SELECT 
    m.id,
    m.user_a,
    m.user_b,
    m.created_at,
    m.unmatched_at,
    (CASE WHEN m.user_a = $1 THEN m.user_b ELSE m.user_a END)::uuid AS other_user_id,
    COALESCE(msg.id, 0)::int8 AS last_message_id,
    COALESCE(msg.body, '')::text AS last_message_body,
    COALESCE(msg.type, '')::text AS last_message_type,
    COALESCE(msg.sender_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS last_message_sender_id,
    msg.created_at AS last_message_created_at
FROM matches m
LEFT JOIN LATERAL (
    SELECT id, body, type, sender_id, created_at
    FROM messages
    WHERE match_id = m.id
    ORDER BY id DESC
    LIMIT 1
) msg ON true
WHERE (m.user_a = $1 OR m.user_b = $1)
  AND m.unmatched_at IS NULL
  AND ($2::timestamptz IS NULL OR m.created_at < $2)
ORDER BY COALESCE(msg.created_at, m.created_at) DESC
LIMIT $3::int4
`

type ListUserMatchesParams struct {
	UserID          uuid.UUID          `json:"user_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	ResultLimit     int32              `json:"result_limit"`
}

type ListUserMatchesRow struct {
	ID                   uuid.UUID          `json:"id"`
	UserA                uuid.UUID          `json:"user_a"`
	UserB                uuid.UUID          `json:"user_b"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UnmatchedAt          pgtype.Timestamptz `json:"unmatched_at"`
	OtherUserID          uuid.UUID          `json:"other_user_id"`
	LastMessageID        int64              `json:"last_message_id"`
	LastMessageBody      string             `json:"last_message_body"`
	LastMessageType      string             `json:"last_message_type"`
	LastMessageSenderID  uuid.UUID          `json:"last_message_sender_id"`
	LastMessageCreatedAt pgtype.Timestamptz `json:"last_message_created_at"`
}

func (q *Queries) ListUserMatches(ctx context.Context, arg ListUserMatchesParams) ([]ListUserMatchesRow, error) {
	rows, err := q.db.Query(ctx, listUserMatches, arg.UserID, arg.CursorCreatedAt, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserMatchesRow{}
	for rows.Next() {
		var i ListUserMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserA,
			&i.UserB,
			&i.CreatedAt,
			&i.UnmatchedAt,
			&i.OtherUserID,
			&i.LastMessageID,
			&i.LastMessageBody,
			&i.LastMessageType,
			&i.LastMessageSenderID,
			&i.LastMessageCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unmatch = `-- name: Unmatch :exec
UPDATE matches
SET unmatched_at = NOW()
WHERE id = $1 AND (user_a = $2 OR user_b = $2)
`

type UnmatchParams struct {
	ID    uuid.UUID `json:"id"`
	UserA uuid.UUID `json:"user_a"`
}

func (q *Queries) Unmatch(ctx context.Context, arg UnmatchParams) error {
	_, err := q.db.Exec(ctx, unmatch, arg.ID, arg.UserA)
	return err
}

const upsertSwipe = `-- name: UpsertSwipe :exec
INSERT INTO swipes (swiper_id, target_id, direction, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (swiper_id, target_id) 
DO UPDATE SET direction = EXCLUDED.direction, created_at = EXCLUDED.created_at
`

type UpsertSwipeParams struct {
	SwiperID  uuid.UUID          `json:"swiper_id"`
	TargetID  uuid.UUID          `json:"target_id"`
	Direction string             `json:"direction"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertSwipe(ctx context.Context, arg UpsertSwipeParams) error {
	_, err := q.db.Exec(ctx, upsertSwipe,
		arg.SwiperID,
		arg.TargetID,
		arg.Direction,
		arg.CreatedAt,
	)
	return err
}
