// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone_e164, status, locale)
VALUES ($1, $2, $3)
RETURNING id, phone_e164, status, created_at, last_active_at, is_premium, premium_until, locale, deleted_at, boost_until
`

type CreateUserParams struct {
	PhoneE164 string `json:"phone_e164"`
	Status    string `json:"status"`
	Locale    string `json:"locale"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.PhoneE164, arg.Status, arg.Locale)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneE164,
		&i.Status,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.IsPremium,
		&i.PremiumUntil,
		&i.Locale,
		&i.DeletedAt,
		&i.BoostUntil,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone_e164, status, created_at, last_active_at, is_premium, premium_until, locale, deleted_at, boost_until
FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneE164,
		&i.Status,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.IsPremium,
		&i.PremiumUntil,
		&i.Locale,
		&i.DeletedAt,
		&i.BoostUntil,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone_e164, status, created_at, last_active_at, is_premium, premium_until, locale, deleted_at, boost_until
FROM users
WHERE phone_e164 = $1 LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneE164 string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneE164)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneE164,
		&i.Status,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.IsPremium,
		&i.PremiumUntil,
		&i.Locale,
		&i.DeletedAt,
		&i.BoostUntil,
	)
	return i, err
}

const purgeDeletedUsers = `-- name: PurgeDeletedUsers :execrows
DELETE FROM users
WHERE deleted_at IS NOT NULL AND deleted_at < $1
`

func (q *Queries) PurgeDeletedUsers(ctx context.Context, deletedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeDeletedUsers, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET status = 'deleted', deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUserLastActive = `-- name: UpdateUserLastActive :exec
UPDATE users
SET last_active_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastActive(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastActive, id)
	return err
}
