// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone_e164, status, locale)
VALUES ($1, $2, $3)
RETURNING id, phone_e164, status, created_at, last_active_at, is_premium, premium_until, locale, deleted_at, boost_until
`

type CreateUserParams struct {
	PhoneE164 string `json:"phone_e164"`
	Status    string `json:"status"`
	Locale    string `json:"locale"`
}

type CreateUserRow struct {
	ID           uuid.UUID          `json:"id"`
	PhoneE164    string             `json:"phone_e164"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	IsPremium    bool               `json:"is_premium"`
	PremiumUntil pgtype.Timestamptz `json:"premium_until"`
	Locale       string             `json:"locale"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	BoostUntil   pgtype.Timestamptz `json:"boost_until"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.PhoneE164, arg.Status, arg.Locale)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.PhoneE164,
		&i.Status,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.IsPremium,
		&i.PremiumUntil,
		&i.Locale,
		&i.DeletedAt,
		&i.BoostUntil,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone_e164, status, created_at, last_active_at, is_premium, premium_until, locale, deleted_at, boost_until
FROM users
WHERE id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID           uuid.UUID          `json:"id"`
	PhoneE164    string             `json:"phone_e164"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	IsPremium    bool               `json:"is_premium"`
	PremiumUntil pgtype.Timestamptz `json:"premium_until"`
	Locale       string             `json:"locale"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	BoostUntil   pgtype.Timestamptz `json:"boost_until"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.PhoneE164,
		&i.Status,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.IsPremium,
		&i.PremiumUntil,
		&i.Locale,
		&i.DeletedAt,
		&i.BoostUntil,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone_e164, status, created_at, last_active_at, is_premium, premium_until, locale, deleted_at, boost_until
FROM users
WHERE phone_e164 = $1 LIMIT 1
`

type GetUserByPhoneRow struct {
	ID           uuid.UUID          `json:"id"`
	PhoneE164    string             `json:"phone_e164"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	IsPremium    bool               `json:"is_premium"`
	PremiumUntil pgtype.Timestamptz `json:"premium_until"`
	Locale       string             `json:"locale"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	BoostUntil   pgtype.Timestamptz `json:"boost_until"`
}

func (q *Queries) GetUserByPhone(ctx context.Context, phoneE164 string) (GetUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneE164)
	var i GetUserByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.PhoneE164,
		&i.Status,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.IsPremium,
		&i.PremiumUntil,
		&i.Locale,
		&i.DeletedAt,
		&i.BoostUntil,
	)
	return i, err
}

const purgeDeletedUsers = `-- name: PurgeDeletedUsers :execrows
DELETE FROM users
WHERE deleted_at IS NOT NULL AND deleted_at < $1
`

func (q *Queries) PurgeDeletedUsers(ctx context.Context, deletedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeDeletedUsers, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET status = 'deleted', deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUserLastActive = `-- name: UpdateUserLastActive :exec
UPDATE users
SET last_active_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastActive(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastActive, id)
	return err
}
