name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Build & Publish Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Build Split-ABI APKs
        working-directory: mobile
        run: |
          flutter pub get
          flutter build apk --flavor prod -t lib/main_prod.dart --split-per-abi --obfuscate --split-debug-info=build/symbols

      - name: Build Production AAB
        working-directory: mobile
        run: flutter build appbundle --flavor prod -t lib/main_prod.dart --obfuscate --split-debug-info=build/symbols

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mobile/build/app/outputs/flutter-apk/*.apk
            mobile/build/app/outputs/bundle/prodRelease/*.aab
          generate_release_notes: true
          draft: false
          prerelease: false
